"use client";

import { useState } from "react";

export function ProfileActions({ reader }: { reader: { slug: string; isOwner: boolean; displayName: string; bio: string; affiliation: string; interests: string[]; viewerFollowing: boolean; followerCount: number } }) {
  const [following, setFollowing] = useState(reader.viewerFollowing);
  const [followers, setFollowers] = useState(reader.followerCount);
  const [editing, setEditing] = useState(false);
  const [profile, setProfile] = useState({ displayName: reader.displayName, bio: reader.bio, affiliation: reader.affiliation, interests: reader.interests.join(", ") });
  const [message, setMessage] = useState("");
  async function follow() { const response = await fetch(`/api/readers/${reader.slug}/follow`, { method: "POST" }); const payload = await response.json() as { following?: boolean; followerCount?: number; signIn?: string; error?: string }; if (response.status === 401 && payload.signIn) { window.location.href = payload.signIn; return; } if (response.ok) { setFollowing(Boolean(payload.following)); setFollowers(payload.followerCount ?? followers); } else setMessage(payload.error ?? "Could not follow reader"); }
  async function save() { const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...profile, interests: profile.interests.split(",") }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? "Profile saved. Refresh to see the public version." : payload.error ?? "Could not save profile"); if (response.ok) setEditing(false); }
  if (!reader.isOwner) return <div className="profile-actions"><button className={`pill-button ${following ? "secondary" : ""}`} onClick={follow}>{following ? "Following" : "Follow reader"}</button><span>{followers} follower{followers === 1 ? "" : "s"}</span>{message && <small>{message}</small>}</div>;
  return <div className="profile-actions"><button className="pill-button secondary" onClick={() => setEditing(true)}>Edit profile</button><span>{followers} follower{followers === 1 ? "" : "s"}</span>{editing && <div className="modal-backdrop"><div className="log-modal" role="dialog" aria-modal="true"><div className="modal-head"><h2>Edit profile</h2><button className="icon-button" onClick={() => setEditing(false)}>×</button></div><label className="form-label">Display name</label><input value={profile.displayName} onChange={(event) => setProfile({ ...profile, displayName: event.target.value })} /><label className="form-label">Affiliation <span className="optional-label">(optional)</span></label><input value={profile.affiliation} onChange={(event) => setProfile({ ...profile, affiliation: event.target.value })} /><label className="form-label">Bio</label><textarea maxLength={500} value={profile.bio} onChange={(event) => setProfile({ ...profile, bio: event.target.value })} /><label className="form-label">Interests <span className="optional-label">(comma separated)</span></label><input value={profile.interests} onChange={(event) => setProfile({ ...profile, interests: event.target.value })} />{message && <p className="form-note">{message}</p>}<div className="form-foot"><span /><button className="pill-button" onClick={save}>Save profile</button></div></div></div>}</div>;
}

export function ListCreator() {
  const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  async function create() { const response = await fetch("/api/lists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, isPublic: true }) }); const payload = await response.json() as { error?: string }; if (response.ok) { setMessage("List created. Refresh to see it here."); setName(""); setDescription(""); } else setMessage(payload.error ?? "Could not create list"); }
  return <div className="list-creator"><button className="pill-button secondary block-button" onClick={() => setOpen((value) => !value)}>Create a paper list</button>{open && <div className="utility-panel"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="List name" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What connects these papers?" /><button className="pill-button" onClick={create}>Create list</button>{message && <small>{message}</small>}</div>}</div>;
}
