"use client";

import { useEffect, useMemo, useState } from "react";
import type { CodeExperience, Paper } from "../../lib/types";

const outcomeLabels: Record<CodeExperience["outcome"], string> = { reproduced: "Reproduced", "partially-reproduced": "Partially reproduced", "did-not-reproduce": "Did not reproduce", "could-not-run": "Could not run" };

export function ReproducibilitySection({ paper }: { paper: Paper }) {
  const [experiences, setExperiences] = useState<CodeExperience[]>([]);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ repositoryUrl: "", commitRef: "", environment: "", dataset: "", outcome: "reproduced" as CodeExperience["outcome"], reproducibilityRating: 0, notes: "", artifactUrl: "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/papers/${paper.id}/code-experiences`).then(async (response) => await response.json() as { experiences?: CodeExperience[] }).then((payload) => setExperiences(payload.experiences ?? [])); }, [paper.id]);
  const own = experiences.find((entry) => entry.isOwner);
  const summary = useMemo(() => { const rated = experiences.filter((entry) => entry.reproducibilityRating); return { average: rated.length ? rated.reduce((sum, entry) => sum + (entry.reproducibilityRating ?? 0), 0) / rated.length : 0, reproduced: experiences.filter((entry) => entry.outcome === "reproduced").length }; }, [experiences]);
  function edit() { if (own) setForm({ repositoryUrl: own.repositoryUrl, commitRef: own.commitRef, environment: own.environment, dataset: own.dataset, outcome: own.outcome, reproducibilityRating: own.reproducibilityRating ?? 0, notes: own.notes, artifactUrl: own.artifactUrl ?? "" }); setError(""); setOpen(true); }
  async function save() {
    setBusy(true); setError("");
    const response = await fetch(`/api/papers/${paper.id}/code-experiences`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, reproducibilityRating: form.reproducibilityRating || null, artifactUrl: form.artifactUrl || null, paper }) });
    const payload = await response.json() as { experience?: CodeExperience; signIn?: string; error?: string };
    if (response.status === 401 && payload.signIn) { window.location.href = payload.signIn; return; }
    if (response.ok && payload.experience) { setExperiences((current) => [payload.experience!, ...current.filter((entry) => !entry.isOwner)]); setOpen(false); } else setError(payload.error ?? "Could not save report");
    setBusy(false);
  }
  async function remove() { if (!confirm("Delete your reproducibility report?")) return; await fetch(`/api/papers/${paper.id}/code-experiences`, { method: "DELETE" }); setExperiences((current) => current.filter((entry) => !entry.isOwner)); setOpen(false); }
  return <section className="repro-section"><div className="logs-head"><div><p className="section-kicker">Code & reproducibility</p><h2>What happened when people ran it</h2></div><button className="pill-button secondary" onClick={edit}>{own ? "Edit your report" : "Report a code experience"}</button></div>
    <div className="repro-summary"><strong>{summary.average ? `${summary.average.toFixed(1)} / 5` : "No score yet"}</strong><span>{experiences.length} code report{experiences.length === 1 ? "" : "s"} · {summary.reproduced} full reproduction{summary.reproduced === 1 ? "" : "s"}</span></div>
    {experiences.length ? experiences.map((entry) => <article className="repro-card" key={entry.id}><div><a className="user-name" href={entry.profileSlug ? `/reader/${entry.profileSlug}` : undefined}>{entry.displayName}</a><span className={`outcome-badge ${entry.outcome}`}>{outcomeLabels[entry.outcome]}</span>{entry.reproducibilityRating && <span className="rating">{"★".repeat(entry.reproducibilityRating)}</span>}</div><a href={entry.repositoryUrl} target="_blank" rel="noreferrer">Repository ↗</a>{entry.commitRef && <code>{entry.commitRef}</code>}<dl>{entry.environment && <><dt>Environment</dt><dd>{entry.environment}</dd></>}{entry.dataset && <><dt>Data</dt><dd>{entry.dataset}</dd></>}</dl>{entry.notes && <p>{entry.notes}</p>}{entry.artifactUrl && <a href={entry.artifactUrl} target="_blank" rel="noreferrer">Evidence / artifact ↗</a>}</article>) : <div className="empty-state"><strong>No structured code reports yet.</strong><br />If you cloned the repository, your outcome can save the next reader hours.</div>}
    {open && <div className="modal-backdrop" role="presentation"><div className="log-modal wide-modal" role="dialog" aria-modal="true" aria-labelledby="repro-title"><div className="modal-head"><h2 id="repro-title">Code experience</h2><button className="icon-button" aria-label="Close" onClick={() => setOpen(false)}>×</button></div><p className="modal-paper">Report what you actually tried. A failed run is useful evidence, not a bad review.</p><label className="form-label">Repository URL</label><input value={form.repositoryUrl} onChange={(event) => setForm({ ...form, repositoryUrl: event.target.value })} placeholder="https://github.com/…" /><div className="two-fields"><label><span className="form-label">Commit / release</span><input value={form.commitRef} onChange={(event) => setForm({ ...form, commitRef: event.target.value })} placeholder="SHA, tag, or date" /></label><label><span className="form-label">Outcome</span><select value={form.outcome} onChange={(event) => setForm({ ...form, outcome: event.target.value as CodeExperience["outcome"] })}>{Object.entries(outcomeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><label className="form-label">Environment</label><textarea className="short-textarea" value={form.environment} onChange={(event) => setForm({ ...form, environment: event.target.value })} placeholder="OS, hardware, runtime and important package versions" /><label className="form-label">Dataset / inputs</label><input value={form.dataset} onChange={(event) => setForm({ ...form, dataset: event.target.value })} placeholder="Dataset name, version, or custom inputs" /><label className="form-label">Reproducibility rating</label><div className="star-picker">{[1,2,3,4,5].map((value) => <button key={value} className={`star-button ${value <= form.reproducibilityRating ? "active" : ""}`} onClick={() => setForm({ ...form, reproducibilityRating: value })}>★</button>)}</div><label className="form-label">Notes</label><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Commands, deviations, errors, metrics, and what worked…" /><label className="form-label">Evidence or artifact URL <span className="optional-label">(optional)</span></label><input value={form.artifactUrl} onChange={(event) => setForm({ ...form, artifactUrl: event.target.value })} placeholder="Public log, notebook, fork, or report" />{error && <p className="form-error">{error}</p>}<div className="form-foot">{own ? <button className="text-button danger" onClick={remove}>Delete report</button> : <span /> }<button className="pill-button" disabled={busy} onClick={save}>{busy ? "Saving…" : "Publish report"}</button></div></div></div>}
  </section>;
}
