import type { Paper } from "./types";

export const paperPictureCatalog: Paper[] = [
  {
    id: "W4384648047",
    title: "Goal-adaptive Meshing of Isogeometric Kirchhoff–Love Shells",
    authors: ["H. M. Verhelst", "A. Mantzaflaris", "M. Möller", "J. H. Den Besten"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-024-01958-4",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-024-01958-4",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Adaptive meshing",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W7119482841",
    title: "Functional maps regularization for high quality mesh morphing applied to shape registration in computed tomography",
    authors: ["Amelia Ferhat", "Henry Proudhon", "Clement Remacha", "David Ryckelynck"],
    year: 2026,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-025-02243-8",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-025-02243-8",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Geometry processing",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4406963414",
    title: "Topology-inclusive aerodynamic shape optimisation using a cellular automata parameterisation",
    authors: ["M. J. Wood", "T. C. S. Rendall", "C. B. Allen", "L. J. Kedward", "N. J. Taylor", "J. Fincham", "N. E. Leppard"],
    year: 2025,
    venue: "Structural and Multidisciplinary Optimization",
    abstract: "",
    doi: "https://doi.org/10.1007/s00158-024-03916-6",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00158-024-03916-6",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Geometric optimization",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W3175823475",
    title: "Be water my friend: mesh assimilation",
    authors: ["Dennis R. Bukenberger", "Hendrik P. A. Lensch"],
    year: 2021,
    venue: "The Visual Computer",
    abstract: "",
    doi: "https://doi.org/10.1007/s00371-021-02183-6",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00371-021-02183-6",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Surface reconstruction",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4376956428",
    title: "Higher-order block-structured hex meshing of tubular structures",
    authors: ["Domagoj Bošnjak", "Antonio Pepe", "Richard Schussnig", "Dieter Schmalstieg", "Thomas-Peter Fries"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-023-01834-7",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-023-01834-7",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Hex mesh generation",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4410797068",
    title: "CADGCL: unsupervised retrieval of CAD models via boundary representations",
    authors: ["Feiwei Qin", "Liangzhe Zhu", "Zijian Xu", "Meie Fang", "Ping Li"],
    year: 2025,
    venue: "The Visual Computer",
    abstract: "",
    doi: "https://doi.org/10.1007/s00371-025-03949-y",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00371-025-03949-y",
    pdfUrl: null,
    citedByCount: -1,
    topic: "CAD retrieval",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4411722294",
    title: "Transformations of computational meshes",
    authors: ["Matthew G. Knepley"],
    year: 2025,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-025-02175-3",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-025-02175-3",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Mesh transformation",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4390851602",
    title: "From CAD to representations suitable for isogeometric analysis: a complete pipeline",
    authors: ["Michelangelo Marsala", "Angelos Mantzaflaris", "Bernard Mourrain", "Sam Whyman", "Mark Gammon"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-024-02065-0",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-024-02065-0",
    pdfUrl: null,
    citedByCount: -1,
    topic: "CAD-to-analysis pipelines",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4407171522",
    title: "Non-iterative generation of optimized meshes for finite element simulations with deep learning",
    authors: ["Martin Legeland", "Kevin Linka", "Roland C. Aydin", "Christian J. Cyron"],
    year: 2025,
    venue: "Machine Learning for Computational Science and Engineering",
    abstract: "",
    doi: "https://doi.org/10.1007/s44379-025-00013-3",
    landingPageUrl: "https://link.springer.com/article/10.1007/s44379-025-00013-3",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Learning-based meshing",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4400347724",
    title: "The generation of tetrahedral meshes for NURBS-enhanced FEM",
    authors: ["Xi Zou", "Sui Bun Lo", "Ruben Sevilla", "Oubay Hassan", "Kenneth Morgan"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-024-02004-z",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-024-02004-z",
    pdfUrl: null,
    citedByCount: -1,
    topic: "NURBS-enhanced meshing",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4400273555",
    title: "Boundary parameter matching for isogeometric analysis using Schwarz–Christoffel mapping",
    authors: ["Ye Ji", "Matthias Möller", "Yingying Yu", "Chungang Zhu"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-024-02020-z",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-024-02020-z",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Geometric parameterization",
    arxivId: null,
    openReviewId: null,
  },
  {
    id: "W4392864955",
    title: "Machine learning mesh-adaptation for laminar and turbulent flows: applications to high-order discontinuous Galerkin solvers",
    authors: ["Kenza Tlales", "Kheir-Eddine Otmani", "Gerasimos Ntoukas", "Gonzalo Rubio", "Esteban Ferrer"],
    year: 2024,
    venue: "Engineering with Computers",
    abstract: "",
    doi: "https://doi.org/10.1007/s00366-024-01950-y",
    landingPageUrl: "https://link.springer.com/article/10.1007/s00366-024-01950-y",
    pdfUrl: null,
    citedByCount: -1,
    topic: "Flow-aware mesh adaptation",
    arxivId: null,
    openReviewId: null,
  },
];

function bareDoi(value: string) {
  return value.trim().toLowerCase().replace(/^doi:\s*/, "").replace(/^https?:\/\/(?:dx\.)?doi\.org\//, "");
}

export function getPaperPicturePaperById(id: string) {
  const normalized = id.trim().toUpperCase();
  return paperPictureCatalog.find((paper) => paper.id === normalized) ?? null;
}

export function getPaperPicturePaperByDoi(doi: string) {
  const normalized = bareDoi(doi);
  return paperPictureCatalog.find((paper) => paper.doi && bareDoi(paper.doi) === normalized) ?? null;
}
